/*
	Copyright 2021 Jordi SUBIRANA

	Permission is hereby granted, free of charge, to any person obtaining a copy of
	this software and associated documentation files (the "Software"), to deal in
	the Software without restriction, including without limitation the rights to use,
	copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
	Software, and to permit persons to whom the Software is furnished to do so, subject
	to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
	OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef ATEMA_MACROLIST_SHADERASTSTATEMENT
#error ATEMA_MACROLIST_SHADERASTSTATEMENT must be defined before including this file
#endif

ATEMA_MACROLIST_SHADERASTSTATEMENT(Conditional)
ATEMA_MACROLIST_SHADERASTSTATEMENT(ForLoop)
ATEMA_MACROLIST_SHADERASTSTATEMENT(WhileLoop)
ATEMA_MACROLIST_SHADERASTSTATEMENT(DoWhileLoop)
ATEMA_MACROLIST_SHADERASTSTATEMENT(VariableDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(StructDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(InputDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(OutputDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(ExternalDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(OptionDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(FunctionDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(EntryFunctionDeclaration)
ATEMA_MACROLIST_SHADERASTSTATEMENT(Expression)
ATEMA_MACROLIST_SHADERASTSTATEMENT(Break)
ATEMA_MACROLIST_SHADERASTSTATEMENT(Continue)
ATEMA_MACROLIST_SHADERASTSTATEMENT(Return)
ATEMA_MACROLIST_SHADERASTSTATEMENT(Sequence)

#undef ATEMA_MACROLIST_SHADERASTSTATEMENT